# Generated by Django 6.0.5 on 2026-05-18 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_lead_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
