# Generated by Django 6.0.5 on 2026-05-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_lead_monthly_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='solar_kwh_required',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
