# Generated by Django 6.0.5 on 2026-05-26 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_lead_solar_kwh_required'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
