# Generated by Django 6.0.5 on 2026-05-28 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_product_project_previous_status_projectproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_date', models.DateField()),
                ('survey_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('site_address', models.TextField()),
                ('maps_link', models.URLField(blank=True, null=True)),
                ('property_type', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Industrial', 'Industrial'), ('Agricultural', 'Agricultural')], default='Residential', max_length=20)),
                ('roof_type', models.CharField(choices=[('RCC', 'RCC (Concrete)'), ('Metal Sheet', 'Metal Sheet'), ('Tin', 'Tin'), ('Ground Mount', 'Ground Mount')], default='RCC', max_length=20)),
                ('roof_age', models.PositiveIntegerField(blank=True, help_text='Years', null=True)),
                ('roof_condition', models.CharField(choices=[('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], default='Good', max_length=10)),
                ('shading', models.CharField(choices=[('None', 'None'), ('Partial', 'Partial'), ('Heavy', 'Heavy')], default='None', max_length=10)),
                ('roof_area', models.DecimalField(blank=True, decimal_places=2, help_text='sq. ft.', max_digits=10, null=True)),
                ('recommended_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('estimated_units', models.DecimalField(blank=True, decimal_places=2, help_text='kWh/month', max_digits=8, null=True)),
                ('panel_orientation', models.CharField(choices=[('South', 'South'), ('East-West', 'East-West'), ('Flat', 'Flat'), ('North', 'North')], default='South', max_length=20)),
                ('shadow_free_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('net_metering', models.BooleanField(default=False)),
                ('discom_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sanctioned_load', models.DecimalField(blank=True, decimal_places=2, help_text='kW', max_digits=6, null=True)),
                ('monthly_bill', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('existing_solar', models.BooleanField(default=False)),
                ('existing_inverter', models.CharField(blank=True, max_length=100, null=True)),
                ('existing_panels', models.CharField(blank=True, max_length=100, null=True)),
                ('photo_roof', models.ImageField(blank=True, null=True, upload_to='survey/roof/')),
                ('photo_meter', models.ImageField(blank=True, null=True, upload_to='survey/meter/')),
                ('photo_surroundings', models.ImageField(blank=True, null=True, upload_to='survey/surroundings/')),
                ('observations', models.TextField(blank=True, null=True)),
                ('special_requirements', models.TextField(blank=True, null=True)),
                ('estimated_install_days', models.PositiveIntegerField(blank=True, null=True)),
                ('recommendation', models.CharField(choices=[('Feasible', 'Feasible'), ('Not Feasible', 'Not Feasible'), ('Needs Review', 'Needs Review')], default='Feasible', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_surveys', to='app.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
