# Generated by Django 6.0.5 on 2026-06-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_ticketotp_ticket_ticketstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='apply_gst',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='apply_subsidy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quote',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='quote',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quote',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quote',
            name='gst_rate',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='quote',
            name='manual_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='subsidy_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quote',
            name='system_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
